baseURL = "https://lgrqvst.com/"
languageCode = "en-us"
title = "Lgrqvst"
theme = "calliope"
# hasCJKLanguage = true
enableEmoji = true
metaDataFormat = "yaml"
paginate = 10
paginatePath = "page"
preserveTaxonomyNames = true

[params]
  authorFirstName = "Johan"
  authorLastName = "Lagerqvist"
  authorFullName = "Johan Lagerqvist"

[taxonomies]
  category = "categories"
  tag = "tags"
  motif = "motifs"
  theme = "themes"

# [permalinks]
  # post = "/:title/"
