name = "Calliope"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://lgrqvst.com/"
tags = []
features = []
min_version = "0.36"

[author]
  name = "Johan Lagerqvist"
  homepage = "https://lgrqvst.com"
